<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractPasswordReset
* @package App\Models\AbstractModels
*
* @property string $email
* @property string $token
* @property \Carbon\Carbon $created_at
*/ 
abstract class AbstractPasswordReset extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'password_resets';
    
    /**  
     * Primary key is non-autoincrementing.
     * 
     * @var bool
     */
    public $incrementing = false;
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'email' => 'string',
        'token' => 'string',
        'created_at' => 'datetime'
    ];
}
