<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractTaskorder
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TONumber
* @property longText $Todescription
* @property string $ContractNo
* @property string $Topnumber
* @property string $Wbsenumber
* @property string $PM
* @property \Carbon\Carbon $Startdate
* @property \Carbon\Carbon $CompletionDate
* @property \Carbon\Carbon $ApprovalDate
* @property string $UniqueNumber
* @property string $Location
* @property bigInteger $TOAmount
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $percentage
* @property integer $customer_invoice_id
* @property \App\Models\CustomerInvoice|null $customerInvoice
*/ 
abstract class AbstractTaskorder extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'taskorders';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TONumber' => 'string',
        'Todescription' => 'string',
        'ContractNo' => 'string',
        'Topnumber' => 'string',
        'Wbsenumber' => 'string',
        'PM' => 'string',
        'Startdate' => 'datetime:Y-m-d',
        'CompletionDate' => 'datetime:Y-m-d',
        'ApprovalDate' => 'datetime:Y-m-d',
        'UniqueNumber' => 'string',
        'Location' => 'string',
        'TOAmount' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'percentage' => 'string',
        'customer_invoice_id' => 'integer'
    ];
    
    public function customerInvoice()
    {
        return $this->belongsTo('\App\Models\CustomerInvoice', 'customer_invoice_id', 'id');
    }
}
