<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractCustomerinvoicess
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $invoicenumber
* @property string $tonumber
* @property bigInteger $toamount
* @property double $invoicepercentage
* @property string $invoicegroup
* @property string $invoicestatus
* @property \Carbon\Carbon $invoicedate
* @property bigInteger $invoiceamount
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractCustomerinvoicess extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'customerinvoicess';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'invoicenumber' => 'string',
        'tonumber' => 'string',
        'toamount' => 'integer',
        'invoicepercentage' => 'double',
        'invoicegroup' => 'string',
        'invoicestatus' => 'string',
        'invoicedate' => 'datetime:Y-m-d',
        'invoiceamount' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
