<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractGrn
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $Suppliername
* @property string $Quotations
* @property string $GRNphysicalcopy
* @property longText $GRNcomments
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractGrn extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'grns';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'Suppliername' => 'string',
        'Quotations' => 'string',
        'GRNphysicalcopy' => 'string',
        'GRNcomments' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
