<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractFailedJob
* @package App\Models\AbstractModels
*
* @property bigInteger $id
* @property string $uuid
* @property text $connection
* @property text $queue
* @property longText $payload
* @property longText $exception
* @property \Carbon\Carbon $failed_at
*/ 
abstract class AbstractFailedJob extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'failed_jobs';
    
    /**  
     * Do not automatically manage timestamps by Eloquent
     * 
     * @var bool
     */
    public $timestamps = false;
    
    /**  
     * The model's default values for attributes.
     * 
     * @var array
     */
    protected $attributes = ['failed_at' => 'NOW()'];
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'uuid' => 'string',
        'connection' => 'string',
        'queue' => 'string',
        'payload' => 'string',
        'exception' => 'string',
        'failed_at' => 'datetime'
    ];
}
