<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractExpensetracker
* @package App\Models\AbstractModels
*
* @property integer $id
* @property double $GeneralExpenses
* @property double $SupplierExpenses
* @property double $SubcontractorExpenses
* @property double $Payroll
* @property double $PettyCashBalance
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractExpensetracker extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'expensetrackers';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'GeneralExpenses' => 'double',
        'SupplierExpenses' => 'double',
        'SubcontractorExpenses' => 'double',
        'Payroll' => 'double',
        'PettyCashBalance' => 'double',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
