<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractTaskordercostss
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TONumber
* @property string $QuotationNumber
* @property string $ItemName
* @property string $ItemUnit
* @property double $TotalAmount
* @property integer $Quantity
* @property double $UnitPrice
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property integer $quotationitem_id
* @property \App\Models\Quotationitem|null $quotationitem
*/ 
abstract class AbstractTaskordercostss extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'taskordercostss';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TONumber' => 'string',
        'QuotationNumber' => 'string',
        'ItemName' => 'string',
        'ItemUnit' => 'string',
        'TotalAmount' => 'double',
        'Quantity' => 'integer',
        'UnitPrice' => 'double',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'quotationitem_id' => 'integer'
    ];
    
    public function quotationitem()
    {
        return $this->belongsTo('\App\Models\Quotationitem', 'quotationitem_id', 'id');
    }
}
