<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractUser
* @package App\Models\AbstractModels
*
* @property bigInteger $id
* @property string $name
* @property string $email
* @property \Carbon\Carbon $email_verified_at
* @property string $password
* @property string $remember_token
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property string $passport_number
*/ 
abstract class AbstractUser extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'users';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'name' => 'string',
        'email' => 'string',
        'email_verified_at' => 'datetime',
        'password' => 'string',
        'remember_token' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'passport_number' => 'string'
    ];
}
