<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractSupplierinvoice
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $SupplierInvoiceNumber
* @property string $LpoNumber
* @property longText $Description
* @property string $SuppliedItems
* @property bigInteger $LpoAmount
* @property string $SupplierName
* @property \Carbon\Carbon $Date
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractSupplierinvoice extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'supplierinvoices';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'SupplierInvoiceNumber' => 'string',
        'LpoNumber' => 'string',
        'Description' => 'string',
        'SuppliedItems' => 'string',
        'LpoAmount' => 'integer',
        'SupplierName' => 'string',
        'Date' => 'datetime:Y-m-d',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
