<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractTaskorderproposal
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TOPNumber
* @property string $TOPTitle
* @property string $Location
* @property string $TOPDocuments
* @property \Carbon\Carbon $SubmissionDate
* @property longText $TOPDescription
* @property double $TOPAmount
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractTaskorderproposal extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'taskorderproposals';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TOPNumber' => 'string',
        'TOPTitle' => 'string',
        'Location' => 'string',
        'TOPDocuments' => 'string',
        'SubmissionDate' => 'datetime:Y-m-d',
        'TOPDescription' => 'string',
        'TOPAmount' => 'double',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
