<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractInvoicetracker
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TONumber
* @property string $TODescription
* @property double $TOAmount
* @property string $Location
* @property string $TOPercetange
* @property string $InvoiceStatus
* @property bigInteger $RemainingBalance
* @property string $InvoiceGroup
* @property string $ReceiptNo
* @property bigInteger $PaidAmount
* @property string $BankName
* @property bigInteger $BudgetBalance
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractInvoicetracker extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'invoicetrackers';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TONumber' => 'string',
        'TODescription' => 'string',
        'TOAmount' => 'double',
        'Location' => 'string',
        'TOPercetange' => 'string',
        'InvoiceStatus' => 'string',
        'RemainingBalance' => 'integer',
        'InvoiceGroup' => 'string',
        'ReceiptNo' => 'string',
        'PaidAmount' => 'integer',
        'BankName' => 'string',
        'BudgetBalance' => 'integer',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
