<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractPurchaseorder
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TONumber
* @property string $QuotationNo
* @property double $TotalAmount
* @property string $SupplierName
* @property string $Description
* @property string $Date
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractPurchaseorder extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'purchaseorders';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TONumber' => 'string',
        'QuotationNo' => 'string',
        'TotalAmount' => 'double',
        'SupplierName' => 'string',
        'Description' => 'string',
        'Date' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
