<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractCustomerInvoice
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $TONumber
* @property string $TOAmount
* @property string $InvoicePercentage
* @property string $InvoiceGroup
* @property string $InvoiceStatus
* @property \Carbon\Carbon $InvoiceDate
* @property double $InvoiceAmount
* @property string $InvoiceNumber
* @property string $ContractNumber
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
* @property \App\Models\Taskorder|null $taskorders
*/ 
abstract class AbstractCustomerInvoice extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'customer_invoices';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'TONumber' => 'string',
        'TOAmount' => 'string',
        'InvoicePercentage' => 'string',
        'InvoiceGroup' => 'string',
        'InvoiceStatus' => 'string',
        'InvoiceDate' => 'datetime:Y-m-d',
        'InvoiceAmount' => 'double',
        'InvoiceNumber' => 'string',
        'ContractNumber' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
    
    public function taskorders()
    {
        return $this->hasOne('\App\Models\Taskorder', 'customer_invoice_id', 'id');
    }
}
