<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractSupplier
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $SupplierName
* @property string $Location
* @property string $SupplierContact
* @property string $SupplierBalance
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractSupplier extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'suppliers';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'SupplierName' => 'string',
        'Location' => 'string',
        'SupplierContact' => 'string',
        'SupplierBalance' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
