<?php
/**
 * Model object generated by: Skipper (http://www.skipper18.com)
 * Do not modify this file manually.
 */

namespace App\Models\AbstractModels;

use Illuminate\Database\Eloquent\Model;

/**
* Class AbstractSubcontractortracker
* @package App\Models\AbstractModels
*
* @property integer $id
* @property string $Subconname
* @property string $Taskorder
* @property double $SubContractorFee
* @property string $SubconPaymentStatus
* @property string $Contractno
* @property string $Tonumber
* @property string $Subcontractordocument
* @property \Carbon\Carbon $created_at
* @property \Carbon\Carbon $updated_at
*/ 
abstract class AbstractSubcontractortracker extends Model
{
    /**  
     * The table associated with the model.
     * 
     * @var string
     */
    protected $table = 'subcontractortrackers';
    
    /**  
     * The attributes that should be cast to native types.
     * 
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'Subconname' => 'string',
        'Taskorder' => 'string',
        'SubContractorFee' => 'double',
        'SubconPaymentStatus' => 'string',
        'Contractno' => 'string',
        'Tonumber' => 'string',
        'Subcontractordocument' => 'string',
        'created_at' => 'datetime',
        'updated_at' => 'datetime'
    ];
}
